# Generated by Django 5.2.12 on 2026-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_artistapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
