# Generated by Django 5.2.12 on 2026-03-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_feedback'),
        ('market', '0011_profile_is_artist'),
    ]

    operations = [
    ]
