# Generated by Django 5.2.12 on 2026-03-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_merge_0010_feedback_0011_profile_is_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistapplication',
            old_name='artist_statement',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='artistapplication',
            old_name='portfolio_url',
            new_name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_artist',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
