# Generated by Django 5.2.12 on 2026-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_artist_statement_artistapplication_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistapplication',
            old_name='description',
            new_name='artist_statement',
        ),
        migrations.RenameField(
            model_name='artistapplication',
            old_name='portfolio_link',
            new_name='portfolio_url',
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='specialization',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='years_of_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
