# Generated by Django 5.2.10 on 2026-03-31 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_profile_is_artist_artistapplication_delete_feedback'),
        ('market', '0014_rename_description_artistapplication_artist_statement_and_more'),
    ]

    operations = [
    ]
