# Generated by Django 4.2.7 on 2026-03-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_contactinquiry'),
        ('market', '0015_merge_20260331_0158'),
    ]

    operations = [
    ]
