# Generated by Django 5.2.10 on 2026-03-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_merge_0013_contactinquiry_0015_merge_20260331_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
